export {default as Navbar} from './Navbar/Navbar.jsx'
export {default as Home} from './Home/Home.jsx';
export {default as Footer} from './Footer';
export {default as About} from './About/AboutUs.jsx'
export {default as OurTeam} from './OurTeam/OurTeam.jsx'
export {default as Services} from './Services/Services.jsx'
export {default as WorkProcess} from './Workprocess/WorkProcess.jsx';
export {default as Portfolio} from  './Portfolio/PortFolia.jsx'
export {default as Contact} from './Contact/Contact.jsx'