export {default as br1} from './branding.png';
export {default as br2} from './br2.png';
export {default as br3} from './br3.png';
export {default as br4} from './br4.png';
export {default as br5} from './br5.png';
export {default as br6} from './br6.png';
export {default as aeroplane} from './aeroplane.png';
export {default as heart} from './heart.png';
export {default as whatsapp} from './whatsappimage.png';
export {default as pencil} from './pencil.png';
export {default as dev1} from './dev1.jpg'
export {default as dev2} from './dev2.jpg'
export {default as dev3} from './dev3.jpg'